### PR TITLE
Update production to model v8.2.0 + deployment maintenance

### PR DESCRIPTION
**Pull request by anngvu**
(just need 1 approving review from anyone who has free time for additional tests)

### Development:
- Catch up on data model releases
- Fix out-of-date rsconnect 

image

- Also address GH Actions deprecation notices -- update versions, removed redundant install in workflow

### Testing in staging https://sagebio.shinyapps.io/NF_data_curator-staging/:
- Generated template for Developing ELISA+IHC... > IHC Data > ImagingAssayTemplate
- Generated and submitted additional metadata for Differentiation of NF1 heterozygous and NF1 homozygous iPS cells > RNAseq data > RNASeqTemplate

### CODE REVIEW

**Comment by jaybee84** [comment]
I generated a manifest for the batch1_WES folder from the Biobank project. Then simply donwloaded the generated manifest and tried to validate it without editing anything but got the following error: 
```
Oops, looks like you have 1 errors !!!
Please check that you have selected the correct template in the Select your Dataset tab and ensure your metadata contains only one template, e.g. Whole Exome Sequencing Assay.
The submitted metadata contains << ‘’ >> in the Component column, but requested validation for << Whole Exome Sequencing Assay >>.
```
Screen Shot 2023-09-28 at 10 50 39 AM

Is this error related to the data model updates?

**Comment by jaybee84** [comment]
I am guessing this is because there are files in addition to fastq files in the folder, and the data model is expecting only one fileformat in the folder being annotated. Is it possible to generate an error message that encourages the user to find a folder with only one file type and then start annotating?

Also, I imagine this will surface this error for many of the older NF projects which have multiple file formats in the same folder.

**Comment by anngvu** [comment]
> Is it possible to generate an error message that encourages the user to find a folder with only one file type and then start annotating?

This is an issue for the DCA.

> Also, I imagine this will surface this error for many of the older NF projects which have multiple file formats in the same folder.

Yeah, we would have to tidy up the files for them.

**Comment by jaybee84** [comment]
@allaway @anngvu @cconrad8 surfacing the conversation in this thread as one potential usecase for the "experiment-centric" data-model. The folder mentioned above was made by the data contributor. It is a single-assay folder i.e. it includes only WES data (since they were instructed to make a separate folder for specific assays), but still retains multiple file types within the same folder since they pertain to the same WES experiment. 
Note: the folder includes auxiliary files (exome bed files) that are a required element of the experiment but not raw data fastq files.

**Pull request merged**
