### PR TITLE
Update deployment

### PR DESCRIPTION
**Pull request by anngvu**
OK, I think deployment is fixed and we can at least generate templates. 
image

Reviewers can go to https://sagebio.shinyapps.io/NF_data_curator-staging/ to do more tests with submission.

To recap, shinyapps updated their platform with a higher python version, so we updated to newer schematic that required higher python version anyway. However, this higher version is 23.6.3 and not yet 24.1.1 because there are other changes needed for 24.1.1 that I'll need to handle. So let's use 23.6.3 for now.

### CODE REVIEW

**Comment by anngvu** [comment]
FYI, there is a known discrepancy in the project drop-down from what I can see from comparison testing, where this project will show up in multi-tenant but not ours. I think there may be some differences in how schematic reads projects in the different versions. But I've been helping this project personally, and so for some of them we can do that until either a complete upgrade to 24.1.1 or transition to mtDCA.
image

**Comment by cconrad8** [comment]
image

Opening works
Creating manifest works
Validation works
Submitting - "disconnect error"

**Comment by anngvu** [comment]
Should be fixed with https://github.com/nf-osi/NF_data_curator/pull/169/commits/8032f126af146efd1a7911aefe91769de4293ebb. 

Submitted annotations look OK.
image

**Comment by allaway** [comment]
Tysm both for working on this!!

On Thursday, February 1, 2024, Anh Nguyet Vu ***@***.***>
wrote:
> Should be fixed with 8032f12.
>
> Submitted annotations look OK.
> image.png (view on web)
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.<
https://ci6.googleusercontent.com/proxy/HPX6pzpUgOy9jhJIqDT_sElTM4ZMbDhJDG_1GIt12j5Z7FnJ0GyiG_jsB7GrFR22bKsKwDbXKt_X6p709lv1b-3kirnTqj-F-8ZPoGOVovifOC5SrpPbPvEaBcC8_Uylbte5sagmWzOvL05FkiKe_5Gb8SmsQnnLxWPr4gXbdxLCzy0zT31HQp5Tffu33ryGhWI4m0wYSKOiTQFyaytdE7C0bZ_NmMZRTxtncu3sdR2AV0CSOQ=s0-d-e1-ft#https://github.com/notifications/beacon/AE3WNSBWJUHUWNDZJLNU5ZDYRQUABA5CNFSM6AAAAABCVPXAH2WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTSS44I6.gif>Message
ID: ***@***.***>

**Comment by cconrad8** [comment]
image
YAY!

**Review by cconrad8 — APPROVED** [review]

**Pull request merged**
