### PR TITLE
Update production with develop branch changes

### PR DESCRIPTION
**Pull request by allaway**
This update incorporates all of the new features from https://github.com/Sage-Bionetworks/data_curator ; major changes are refreshed UI, OAuth-based login, app restructuring into separate app files, and makes some local tweaks to accommodate our project/data structure. 

@anngvu - could you test the staging app (https://shiny.synapse.org/users/rallaway/NF_data_curator_staging/) and check if login, manifest generation, manifest validation, and annotation upload (using the `Neurofibromatosis Demo` project) all work ok on this new version?

After merging and pulling to shiny server, the OAuth `client_id` and `client_secret` for the production app will need to be added to the configuration file to make the app work.

### CODE REVIEW

**Review by anngvu — COMMENTED** [review]
:heavy_check_mark: access works with and without being already logged in
:heavy_check_mark: sample [manifest](https://docs.google.com/spreadsheets/d/1C_Wy2Ns1dSKGexVvLWQdk8_RY2Ytqi1R7B5D17Ilx6k/edit#gid=0) creation and validation
:heavy_check_mark: sample manifest upload successful

**Review by anngvu — APPROVED** [review]

**Comment by allaway** [comment]
@anngvu discovered in review that the file annotations were being converted to PascalCase, I had forgotten to add the `associateMetadataWithFiles` parameter `useSchemaLabel = FALSE` - I've done that now. 

Also noticed that the ETag and Filename were being added as annotations. Upgrading to `develop` schematic should fix this (https://github.com/Sage-Bionetworks/schematic/pull/479)

**Comment by allaway** [comment]
Turns out I was also missing the `getModelManifest` `useAnnotations = T` parameter - this pulls the current annotations from the files when generating a manifest

**Comment by allaway** [comment]
Updated the `data_curator_env_oauth` conda environment to the current develop version of schematic (`python -m pip install git+https://github.com/Sage-Bionetworks/schematic@develop`)

**Comment by allaway** [comment]
OK- One more thing - there was a schematic bug that is only apparent when `use_annotations=T`, fixed upstream: https://github.com/Sage-Bionetworks/schematic/pull/530

**Comment by allaway** [comment]
I'll wait till tomorrow before pulling the changes into the Shiny server because I've learned the hard way that end of the day shiny updates are guaranteed to break....

**Pull request merged**
