### PR TITLE
Merge develop into production

### PR DESCRIPTION
**Pull request by anngvu**
The rules are set up so that we need one approving review for merging into production. Since Robert is out, please go to staging https://sagebio.shinyapps.io/NF_data_curator-staging/ and validate to make sure your requested specific fixes are there, or just more generally test if you have time (i.e. @cconrad8 is optional backup).

@jaybee84 -- this should resolve https://github.com/nf-osi/nf-metadata-dictionary/issues/245 and the `weblink` addition. 

Note: if you have get something like: "worker timed out when trying to connect", just refresh -- I think shinyapps.io is being slow.

### CODE REVIEW

**Comment by anngvu** [comment]
image

Is it just me, or is the "edit" selection new? Hmm.

**Comment by jaybee84** [comment]
It is new IIRC... and you were not kidding about shinyapps being slow!

**Comment by jaybee84** [comment]
The additions look good to me. 

Any idea what the highlighted columns are in the attached image?
Screen Shot 2023-01-25 at 2 44 48 PM

**Comment by anngvu** [comment]
@jaybee84 Not sure -- if you give me the parent syn id, can take a look at those data files. I suspect they might be extra annotations (row numbers) that were added using R previously.

**Comment by jaybee84** [comment]
This is the` parentid` : `syn43697068` for the above manifest

**Review by jaybee84 — APPROVED** [review]

**Comment by anngvu** [comment]
OK, still suspecting that Yang has been annotating using R and reading in a table with row names. We can clean up those but just making sure first.

**Pull request merged**
