### PR TITLE
update logo and add icon

### PR DESCRIPTION
**Pull request by kthrog**
Major changes:

- new NF-OSI logo added
- logo now links to NF-OSI info on [Synapse](https://www.synapse.org/#!Wiki:syn17083165/ENTITY/591007)
- NF-OSI logo icon now the favicon (browser tab icon)

This should resolve issues #14, #15, and #12.

See changes live on [staging](https://shiny.synapse.org/users/rallaway/NF_data_curator_staging/).

### CODE REVIEW

**Comment by allaway** [comment]
Does this include changes to app.R that you might have made on the shiny server? It looks like that still references the old png, not the new one.

**Comment by kthrog** [comment]
I see now that it does not! I thought I pushed those and included them in this PR, but apparently not. Let me do that now.

**Comment by kthrog** [comment]
Should be good to go now!

**Review by allaway — CHANGES_REQUESTED** [review]
Can you remove the `www/nflogo_whitebkgrd.png`, `www/nfosi_logo.png`?

I also see that schematic was pushed as a submodule. I think this just links the two repositories....but not sure. I think we can always remove it later if needed (i'm just not sure whether this will make the git pulls/pushes happen in both repositories or not....not super familiar with submodules)

**Comment by kthrog** [comment]
Done! All images not currently in use have been removed from `www`

Also, did you mean to delete restart.txt? :) 

And I have _no idea_ how I added schematic as a submodule. Whoops!? It does look like they're linked, but if it causes issues later, happy to remove.

**Comment by allaway** [comment]
> Done! All images not currently in use have been removed from `www`

Thanks!

> Also, did you mean to delete restart.txt? :)

Yup, it's not really necessary to store in github...just keeping things tidy, but omitting it's just personal preference more than anything really meaningful. :)

**Review by allaway — APPROVED** [review]
LGTM!

**Comment by kthrog** [comment]
Pulled this into the app -- and it looks good! That schematic submodule didn't seem to affect anything, but I'll continue to monitor.

**Pull request merged**
