### PR TITLE
Update production app

### LINKED ISSUE #100: App breaks with too many validation errors
**Describe the bug**
Somewhere between 8 errors (works fine) and 250 errors, the app crashes with the following error, presumably when trying to render the validation errors data table: 

`DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Pulling in the upstream data curator app changes might address this, I know there were a bunch of stability and other improvements made.

### LINKED ISSUE #137: Alphabetically arrange all options in all the columns
**Describe the bug**
In the manifest, when I select a dropdown menu, the options are not alphabetically arranged.

**To Reproduce**
1. Go to manifest
2. Click on dataType
3. Scroll down to explore all options
4. Options are not alphabetically arranged

**Expected behavior**
All options in any of the dropdown lists should be alphabetically arranged

**Priority** (select one)
- [ X] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

### PR DESCRIPTION
**Pull request by allaway**
This update:
- pins schematic to the latest pip release when the build is on `production` or on a numbered/versioned release. 
- development/testing versions of the app build on latest develop branch of schematic 
❓: do we want this? an alternative might be to have production/develop apps build on the pip release of schematic, and testing1 app build on `develop` schematic. 
❓: do we want to pin `main` more explicitly in the workflow, rather than pulling in the latest pip release? this could avoid unexpected app breaking
- updates the DCA to the latest version, compatible with schematic 22.10.1 
❓: the workflow builds a config file for us, so we don't have to maintain all of the manifest types. this is currently disabled because there are two issues (1) the new config file that is built doesn't have a main_fileview value, which breaks server.R, and (2) I am not sure if our schema (haven't investigated) is configured correctly to do this, details here: https://github.com/Sage-Bionetworks/data_curator/releases/tag/v22.09.1

After this is merged, we'll want to release an updated version of nf-metadata-dictionary that incorporates changes in https://github.com/nf-osi/nf-metadata-dictionary/pull/201/, to avoid trailing comma validation issues with list attributes. 

Edit:

Fixes #137 
Fixes #100

### CODE REVIEW

**Comment by allaway** [comment]
The app with schema v2.6.0 should be available for testing soon here: https://sagebio.shinyapps.io/NF_data_curator-testing1/

**Comment by anngvu** [comment]
> ❓: do we want this? an alternative might be to have production/develop apps build on the pip release of schematic, and testing1 app build on develop schematic.
> ❓: do we want to pin main more explicitly in the workflow, rather than pulling in the latest pip release? this could avoid unexpected app breaking

Yeah, I think deploy configuration should be

| schematic               | data model        | shiny app label | comment  |
|----------------------|-------------------| -----------------| -----------------|
| pinned pip release (likely *not* even the most recent release)   | pinned version that has already been staged   | `NF_data_curator` (prod) | when commit to `main`, workflow deploys by installing using the pinned release
| pinned pip release same as `prod`   | updated data model version   | `NF_data_curator-staging`                  | well-understood schematic version + updated data model
| more recent pip release *or* most recent commit in `develop` | updated data model version    | `NF_data_curator-testing1` | when data model changes *require* updating the schematic version, and for looking ahead

So I think in terms of some workflow rewriting:
- new release tag of data model triggers updating config in `develop` branch
- that triggers two deployments: 
   1) to `staging` app, which install the pinned version of schematic
   2) to `develop` app, which installs some newer version of schematic
- if staging looks good, merge `develop` into `prod`, which triggers `production` deployment.
- for `develop` deployment, "some newer version" means if there is more recent tag in main than the one currently used for `prod`, use that, otherwise, use the latest develop commit. (I think we should avoid updating schematic unless we *really* need the new feature.)

**I can rewrite the deploy workflow** to reflect this if you agree -- should it go into this PR, or do you want to merge this first and take care of it in a later PR?

> the workflow builds a config file for us, so we don't have to maintain all of the manifest types. this is currently disabled 

If it breaks things, then yes, good thing you're disabling it! I also don't think we've been wanting to surface all the manifest types necessarily, so in this case manual control is fine.

**Comment by allaway** [comment]
> I can rewrite the deploy workflow to reflect this if you agree -- should it go into this PR, or do you want to merge this first and take care of it in a later PR?

Thanks so much! I agree with this approach, I think it is safer/less likely to break than the workflow as currently written in this PR. Regarding whether we should merge this first or take care of it later, it would be nice to get this PR merged soonish so that we can (finally) get the production app off of the old branch off of schematic. It will be nice to get the proper list like validation incorporated as well instead of my hacky fix. If we go with this workflow for a few days, I think it is unlikely we'll break anything; as long as we have an updated workflow merged in within the next couple of weeks (i.e. I don't believe we risk breaking anything until we have both a new schematic pip release _and_ a new data model release triggering a rebuild of the app). 

> If it breaks things, then yes, good thing you're disabling it! 

I had to discover it the hard way :) 

> I also don't think we've been wanting to surface all the manifest types necessarily, so in this case manual control is fine.

Makes sense - happy to keep it this way then!

**Review by anngvu — APPROVED** [review]
Did interactive user testing to generate manifests and validate. Doesn't validate with `cellType` being blank, but that is expected until the data model update...

**Pull request merged**
