### PR TITLE
First deployment!

### LINKED ISSUE #3: add compatibility for subfolders
Right now, the app can only inspect top-level folders; need to add ability to browse subfolders as well...not clear what the best strategy for this is. Could allow user to directly input synapse id of folder, or could simply pull all Folder objects for a the selected project from the main fileview. Latter probably easier.

### PR DESCRIPTION
**Pull request by allaway**
Ok, I think we actually have a minimum viable product now, but can you walk through and test? 

If you walk through the app and note possible improvements, can you file them as issues (no need to be exhaustive). 

As long as the app works relatively well (i.e. better than the current production site), then I am comfortable pushing this to production, but LMK what you think!

edit: closes #3 now

### CODE REVIEW

**Comment by allaway** [comment]
Added some more functionality to this PR: 

`waiters` on the get manifest and validate manifest actions to prevent more than one click of the respective buttons, and as a more pronounced status update for user
modified the way the app looks for folders - now it will look for every folder in the selected project. This is better for NF, where we have data often beyond the top-level of folders. However, it introduces a new problem: what if the user has data across many subfolders that they'd like to annotate at once (there are a few examples of this in NF)? We'd need to add support for selecting multiple folders, enable adding files by entire project, or by enabling recursive identification of files. This can probably be pretty easily achieved with `synapseutils.walk.walk()`

**Comment by allaway** [comment]
closes #3

**Comment by allaway** [comment]
you can deploy after merging by: 

1. ssh into shiny server
2. `cd /home/rallaway/ShinyApps/NF_data_curator` (you should have access now, if not reach out to xa)
3. `git branch` (just to check that `production`is checked out)
4. `git pull` 
5.  `touch restart.txt`

**Comment by kthrog** [comment]
Merging this now, and will note any issues after I try to deploy.

**Review by kthrog — APPROVED** [review]

**Comment by kthrog** [comment]
Initial error when deploying, due to the config.yml being deleted. Will try to re-add this file and then re-deploy. 

Log below: 
```
Error in py_run_file_impl(file, local, convert) :
  FileNotFoundError: [Errno 2] No such file or directory: '/home/rallaway/ShinyApps/NF_data_curator/schematic/config.yml'
```

**Comment by kthrog** [comment]
Yikes, well, after deploying this, it brought down the whole app (and staging, too!), and it's just been whack-a-mole with issues in the log files since. I'm not completely sure how/why this happened -- at first I thought it was just related to the deletion of the config file (as that's what the first log file showed, but when I tried re-adding, that didn't fix anything; I also see now that file lives in the schematic repo, which is why I'm assuming it was deleted). 

Will try to troubleshoot this more tomorrow. May revert the merge, and work my way back out again.

**Comment by allaway** [comment]
I think this was due to my bad instructions. I neglected to mention that you'll also need to merge https://github.com/nf-osi/schematic/pull/4 and then

```
cd /home/rallaway/ShinyApps/NF_data_curator/schematic (you should have access now, if not reach out to xa)
git branch (just to check that production is checked out)
git pull
```

as well! reset both the production and and staging apps to their state earlier this week ,so they should be all good again. Feel free to try again, apologies for omitting the `schematic` instructions!

**Comment by kthrog** [comment]
No worries, I'll give this a try now. I had a feeling `schematic` was involved. Although... aren't you supposed to be on vacation and not commenting on PRs!? :)

**Comment by allaway** [comment]
🙊

**Comment by kthrog** [comment]
Okay, ran into a couple permissions issues along the way when pulling and restarting Shiny (reached out to Xa but haven't heard back), but they must've been minor/non-blocking because from what I can tell, the app is up and running smoothly! Filename is even showing up where it's supposed to be, all the way to the left in the generated manifest!
The only thing I didn't try is uploading back to Synapse, mostly because I haven't managed to fill out a properly-validated file yet (the test one I'm using has a gazillion errors). But I'll get to that Monday.

**Pull request merged**
